// One-off: shrink the oversized AI-generated PNGs into web-weight JPGs.
// The 4K entry painting (~14 MB) was the cause of the multi-second splash freeze
// — Next re-optimizes the source on every dev request. These light sources let
// next/image serve appropriately-sized AVIF/WebP without the giant decode.
// Also regenerates src/components/entry/blur.ts (the inline blur placeholders)
// from the optimized JPGs.
// Run: node scripts/optimize-entry.mjs                (everything)
//      node scripts/optimize-entry.mjs --blur-only    (just blur.ts)
import sharp from "sharp";
import { stat, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const PUB = new URL("../public/", import.meta.url);
const path = (rel) => fileURLToPath(new URL(rel, PUB));

// [source, output, target width, quality]
const JOBS = [
  // entry/splash backgrounds — the actual freeze
  ["entry/entry-hd.png", "entry/entry-hd.jpg", 2560, 85],
  ["entry/entry-hd-portrait.png", "entry/entry-hd-portrait.jpg", 1440, 85],
  // other heavy landing PNGs (§5 — overall "heaviness" win)
  ["entry/close-desktop.png", "entry/close-desktop.jpg", 1672, 85],
  ["entry/wide-desktop.png", "entry/wide-desktop.jpg", 1672, 85],
  ["entry/hero.png", "entry/hero.jpg", 941, 88],
  ["entry/hero-poster.png", "entry/hero-poster.jpg", 820, 88],
];

const kb = (n) => `${(n / 1024).toFixed(0)} KB`;
const blurOnly = process.argv.includes("--blur-only");

if (!blurOnly) {
  for (const [src, out, width, quality] of JOBS) {
    const srcPath = path(src);
    const outPath = path(out);
    const before = (await stat(srcPath)).size;
    await sharp(srcPath)
      .resize({ width, withoutEnlargement: true })
      .jpeg({ quality, mozjpeg: true })
      .toFile(outPath);
    const after = (await stat(outPath)).size;
    console.log(
      `${src}  ${kb(before)} -> ${out}  ${kb(after)}  (${(100 - (after / before) * 100).toFixed(0)}% smaller)`,
    );
  }
}

// ---- blur placeholders (inlined into the landing HTML + JS bundle, so keep
// them TINY — they only cover the beat before the preloaded painting arrives)
// kept tiny on purpose — the underlays apply a CSS blur() when displaying these,
// so the upscale reads as soft focus, never JPEG blocks
const BLUR_JOBS = [
  ["entry/entry-hd.jpg", "BLUR_DESKTOP", 200],
  ["entry/entry-hd-portrait.jpg", "BLUR_PORTRAIT", 140],
];

let blurTs =
  "// Auto-generated by scripts/optimize-entry.mjs — do not edit by hand.\n" +
  "// Tiny inline previews for the entry painting: they paint instantly (no green\n" +
  "// frame) and upscale soft, then the preloaded sharp image fades in over them.\n";
for (const [src, name, width] of BLUR_JOBS) {
  const buf = await sharp(path(src))
    .resize({ width })
    .jpeg({ quality: 60, mozjpeg: true })
    .toBuffer();
  blurTs += `export const ${name} =\n  "data:image/jpeg;base64,${buf.toString("base64")}";\n`;
  console.log(`${src} -> blur.ts ${name}  ${kb(buf.length)}`);
}
await writeFile(
  fileURLToPath(new URL("../src/components/entry/blur.ts", import.meta.url)),
  blurTs,
);
